// Package emit generates .go source files from the database.
// This is the inverse of ingest — it emits the database back into
// files that `go build` can compile.
package emit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/justinstimatze/defn/internal/store"
)

// DefLocation records where a definition was placed in an emitted file,
// so diagnostics can be mapped back to defn terms.
type DefLocation struct {
	DefID     int64
	DefName   string
	Kind      string
	Module    string
	File      string // emitted file path
	StartLine int    // 1-based line in emitted file where body begins
	EndLine   int    // 1-based line in emitted file where body ends
}

// Emit writes all definitions from the database as .go files into outDir.
// Each module becomes a directory, and definitions are grouped into files by kind.
func Emit(db *store.DB, outDir string) error {
	_, err := EmitWithMap(db, outDir)
	return err
}

// EmitWithMap is like Emit but also returns a source map: for each emitted
// line, which definition it belongs to. This powers defn lint.
func EmitWithMap(db *store.DB, outDir string) ([]DefLocation, error) {
	var allLocs []DefLocation

	modules, err := db.ListModules()
	if err != nil {
		return nil, fmt.Errorf("list modules: %w", err)
	}

	for _, mod := range modules {
		locs, err := emitModule(db, &mod, outDir)
		if err != nil {
			return nil, fmt.Errorf("emit %s: %w", mod.Path, err)
		}
		allLocs = append(allLocs, locs...)
	}

	return allLocs, nil
}

func emitModule(db *store.DB, mod *store.Module, outDir string) ([]DefLocation, error) {
	defs, err := db.GetModuleDefinitions(mod.ID)
	if err != nil {
		return nil, err
	}
	if len(defs) == 0 {
		return nil, nil
	}

	// Group definitions by kind for file organization.
	// types.go, functions.go, methods.go, etc.
	groups := map[string][]store.Definition{}
	for _, d := range defs {
		key := fileForKind(d.Kind)
		groups[key] = append(groups[key], d)
	}

	// Determine output directory from module path.
	// Strip the module root to get relative path.
	pkgDir := filepath.Join(outDir, mod.Name)
	if err := os.MkdirAll(pkgDir, 0755); err != nil {
		return nil, err
	}

	var allLocs []DefLocation
	for filename, fileDefs := range groups {
		path := filepath.Join(pkgDir, filename)
		locs, err := writeFile(path, mod.Name, mod.Path, fileDefs)
		if err != nil {
			return nil, err
		}
		allLocs = append(allLocs, locs...)
	}

	return allLocs, nil
}

func writeFile(path, pkgName, modulePath string, defs []store.Definition) ([]DefLocation, error) {
	var buf strings.Builder
	var locs []DefLocation

	buf.WriteString("// Code generated by defn emit; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	line := 3 // next line to be written (1-based)

	for i, d := range defs {
		if d.Doc != "" {
			docLines := strings.Split(strings.TrimSpace(d.Doc), "\n")
			for _, dl := range docLines {
				buf.WriteString("// " + dl + "\n")
				line++
			}
		}
		bodyStart := line
		bodyLines := strings.Count(d.Body, "\n") + 1
		buf.WriteString(d.Body)
		buf.WriteString("\n")
		line += bodyLines

		locs = append(locs, DefLocation{
			DefID:     d.ID,
			DefName:   d.Name,
			Kind:      d.Kind,
			Module:    modulePath,
			File:      path,
			StartLine: bodyStart,
			EndLine:   line - 1,
		})

		if i < len(defs)-1 {
			buf.WriteString("\n")
			line++
		}
	}

	return locs, os.WriteFile(path, []byte(buf.String()), 0644)
}

func fileForKind(kind string) string {
	switch kind {
	case "type", "interface":
		return "types.go"
	case "function":
		return "functions.go"
	case "method":
		return "methods.go"
	case "const":
		return "constants.go"
	case "var":
		return "vars.go"
	default:
		return "other.go"
	}
}
